name: nyx_converter
version: 1.0.0
description: >-
  Flutter package for audio and video conversion, media info, thumbnails, and
  real-time FFmpeg progress tracking.

repository: https://github.com/xaus-group/nyx_converter
issue_tracker: https://github.com/xaus-group/nyx_converter/issues
homepage: https://xaus-group.github.io/nyx_converter/

topics:
  - video
  - audio
  - converter
  - ffmpeg
  - media

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.27.3"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^4.6.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

assets:
  - assets/videos/

screenshots:
  - description: The flutter nyx_converter package logo.
    path: screenshots/logo.png
