name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get package dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Get example dependencies
        working-directory: example
        run: flutter pub get

      - name: Run integration tests
        working-directory: example
        run: flutter test integration_test
